### ISSUE TITLE
MultipartNodeUploadAPI.js errors on CompleteMultipartUpload

### ISSUE THREAD

**Issue by rashwell** [Panopto/UploadAPISamples#1]
Does this API still work with Panopto?  I can almost get the example to work.  I am working against our own hosted panopto service, The authentication succeeds, The session gets created and in the end shows up on the service, in the appropriate folder.  Each of the slices upload, but when posting the closing upload xml with the multipart etag stuff, which I have verified is formatted correctly, I still get an error returned of the XML you provided was not well-formed or did not validate against our published schema.  Does this example need updating because of some API change?  Or is it possible I am missing something.

**Comment by hohno-panopto** [comment]
Sorry for very slow response. This was fixed by #2
